spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:haul;MODE=MYSQL
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #  show_sql: true
        format_sql: true
        use_sql_comments: true